DefaultContentLanguage = "fr"
theme = "boot"
relativeURLs = true
googleAnalytics = "UA-152851764-2" # Your Analytics ID here
baseURL = "/"
title = "GOLDSTANDARDSITES"

[languages]
    [language.fr]
        languageName = "Français"
        weight = 1
        description = "Le Standard Des Sites Pour Petites Entreprise"
    [[menu]]
        [[menu.fr.mainmenu]]
            url = "/"
            name = "Accueil"
            weight = 1


    [language.en]
        languageName = "English"
        weight = 2
        title = "GOLDSTANDARDSITES"
        description = "The Gold Standard For Small Business Sites"
    [[menu]]
    [[menu.en.mainmenu]]
        url = "/"
        name = "Home"
        weight = 1


[params]
    # Schema Information
    businessname = "Company Name"
    type = "LocalBusiness" # Enter Your Type of business - schema.org
    pricerange = "2" # Enter Your Price range 1 to 5
    reviewcount = "5" # How many reviews you've got
    reviewvalue = "4.5" # Average ratings on Yelp & Google
    reservation = "true" # Do you accept reservations? Enter true or false
    openinghour = "Mo-Sa 11:00-22:00" # Opening Hours
    address = "123 Sample Street" # Enter Address Here
    city = "Rigaud" # Enter City
    region = "QC" # Enter State or Province Here
    country = "Canada" #Enter Country Here
    postalcode = "J0P 1P0" # Enter Postal Code
    phone = "+1-123-456-7890" # Enter Phone Number
    email = "info@goldstandardsites.com" # Enter Your Email
    facebookurl = "https://www.facebook.com/"
    instagram = "https://instagram.com/"
    logo = "img/logo.png"
    image = "img/og.png" # Ideal 1200 x 630 for schema + og